const { ObjectId } = require('mongodb');

class ChatHistoryService {
  constructor(mongoClient) {
    this.mongoClient = mongoClient;
    this.dbName = 'test';
    this.collectionName = 'chat_history';
  }

  getCollection() {
    return this.mongoClient.db(this.dbName).collection(this.collectionName);
  }

  /**
   * Save a user message and bot response pair to the history.
   * @param {string|ObjectId} userId - The user's _id from the users collection
   * @param {string} userMessage - The message sent by the user
   * @param {string} botResponse - The response generated by the bot
   */
  async saveMessage(userId, userMessage, botResponse) {
    try {
      const collection = this.getCollection();
      await collection.insertOne({
        userId: userId.toString(),
        userMessage,
        botResponse,
        timestamp: new Date(),
      });
    } catch (error) {
      console.error('Error saving chat message to history:', error);
      // Non-fatal: do not throw, just log
    }
  }

  /**
   * Retrieve full chat history for a user, sorted oldest-first.
   * @param {string|ObjectId} userId
   * @returns {Array<{userMessage, botResponse, timestamp}>}
   */
  async getHistory(userId) {
    try {
      const collection = this.getCollection();
      const history = await collection
        .find({ userId: userId.toString() })
        .sort({ timestamp: 1 })
        .toArray();
      return history;
    } catch (error) {
      console.error('Error retrieving chat history:', error);
      return [];
    }
  }

  /**
   * Delete all chat history for a given user (used on account deletion).
   * @param {string|ObjectId} userId
   */
  async deleteHistory(userId) {
    try {
      const collection = this.getCollection();
      const result = await collection.deleteMany({ userId: userId.toString() });
      console.log(`Deleted ${result.deletedCount} chat history records for user ${userId}`);
    } catch (error) {
      console.error('Error deleting chat history:', error);
      throw error;
    }
  }
}

module.exports = ChatHistoryService;
